package builder.structures.oriental.magistrate;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class JapanMagistrate1
{
	/** Some predefined values for custom hooks that I use in the demo 
	 * structure 
	 **/
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayMagistrate1 =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{0},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{0},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 2
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 4
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 5
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 6
				{Block.torchWood.blockID, 4},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 7
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.torchWood.blockID, 3},
			},
			{//x = 8
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 9
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 10
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 11
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 12
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 13
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 14
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 15
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 16
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 17
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 18
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 19
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 20
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 21
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 22
				{Block.torchWood.blockID, 4},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.torchWood.blockID, 3},
			},
			{//x = 23
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 24
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 25
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 26
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 27
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
			},
			{//x = 28
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{0},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{0},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{0},
				{0},
			}			
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 5
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 8
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 9
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 10
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 12
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 18
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 19
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 20
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 21
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 22
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 23
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 24
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 25
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 26
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 27
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
			},
			{//x = 28
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.woodenButton.blockID, 2},
				{Block.stone.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 3
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 5
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.waterStill.blockID, 3},
				{Block.waterStill.blockID, 2},
				{Block.waterStill.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 6
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.waterStill.blockID, 2},
				{Block.waterStill.blockID, 1},
				{Block.waterStill.blockID, 9},
				{Block.waterStill.blockID, 8},
				{Block.stainedClay.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 7
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.waterStill.blockID, 3},
				{Block.waterStill.blockID, 2},
				{Block.waterStill.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 8
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 9
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 10
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 11
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 12
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 17},
				{0},
				{Block.wood.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 19},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 19},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 21},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 18
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 19
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 20
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 21
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 22
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 23
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 24
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 25
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 26
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 27
				{0},
				{Block.woodenButton.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3},
				{0},
			},
			{//x = 28
				{0},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.stone.blockID},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.woodenButton.blockID, 1},
				{Block.stone.blockID},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.waterStill.blockID, 1},
				{Block.waterStill.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 26
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 28
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}