package builder.structures.roman;

import net.minecraft.block.Block;

public class RomanInn2
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116;

	public static final int[][][][] blockArrayRomanInn2 =
	{
		{//y = 11
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.trapdoor.blockID, 1},
				{Block.sandStone.blockID},
				{Block.trapdoor.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.trapdoor.blockID, 2},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 12
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{0},
				{Block.trapdoor.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 6
				{Block.trapdoor.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 3},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 3},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 13
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 3
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 5
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 6
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 7
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 9
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 10
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			}
		},
		{//y = 14
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 5
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 6
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.sandStone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 15
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.sandStone.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.sandStone.blockID},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 16
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 17
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}