package builder.structures.medieval.alchemisttower;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class AlchemistTower1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;
	
	public static final int[][][][] blockArrayAlTower =
	{
		{//y = 0
			{//x = 0
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 1
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.glowStone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 16
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.glowStone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 17
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 18
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 19
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 20
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID}
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 2
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0}
			},
			{//x = 13
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 27},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID}
			},
			{//x = 14
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneBrick.blockID}
			},
			{//x = 15
				{Block.stoneBrick.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.cobblestone.blockID}
			},
			{//x = 16
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 17
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID}
			},
			{//x = 18
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.signPost.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0}
			},
			{//x = 1
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 1
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0}
			},
			{//x = 13
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 14
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{0}
			},
			{//x = 15
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0}
			},
			{//x = 16
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0}
			},
			{//x = 17
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3}
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0}
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0}
			},
			{//x = 14
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0}
			},
			{//x = 15
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0}
			},
			{//x = 16
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0}
			},
			{//x = 17
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.brick.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 14
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 15
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0}
			},
			{//x = 16
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.brick.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.brick.blockID},
				{Block.brick.blockID},
				{Block.brick.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 14
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0}
			},
			{//x = 15
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0}
			},
			{//x = 16
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0}
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.brick.blockID},
				{Block.brick.blockID},
				{Block.brick.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 11
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.brick.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 14
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 15
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.brick.blockID},
				{0},
				{0}
			},
			{//x = 16
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.brick.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 12
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 14
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 15
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0}
			},
			{//x = 16
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0}
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 13
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 12
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 13
				{0},
				{0},
				{Block.fence.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 14
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 15
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 16
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0}
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.glowStone.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 18
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0}
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}