package builder.structures.medieval.twos;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class GuardTower1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayGuardTower1 =
	{
		{//y = 0
			{//x = 0
				{Block.stone.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.stone.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.stone.blockID},
			},
			{//x = 1
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
			},
			{//x = 2
				{Block.gravel.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.gravel.blockID},
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
			},
			{//x = 3
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 4
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 5
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 6
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 7
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 8
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
			},
			{//x = 10
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
			},
			{//x = 11
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
			},
			{//x = 12
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{Block.stone.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
			},
			{//x = 2
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 3
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 4
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.lever.blockID, 13, 0},
				{Block.lever.blockID, 13, 0},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 5
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.lever.blockID, 14, 0},
				{Block.lever.blockID, 14, 0},
				{Block.dirt.blockID},
				{0},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 6
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 7
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
			},
			{//x = 8
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.pistonBase.blockID, 9, 0},
				{Block.pistonBase.blockID, 9, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.pistonBase.blockID, 9, 0},
				{Block.pistonBase.blockID, 9, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.doorWood.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.pistonExtension.blockID, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.cobblestone.blockID},
				{Block.furnaceBurning.blockID, 3, 0},
				{0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.pistonExtension.blockID, 1, 1},
				{0},
				{SPAWN_VILLAGER, 1, 28},
				{0},
				{0},
				{Block.furnaceBurning.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.cobblestone.blockID},
				{Block.furnaceBurning.blockID, 3, 0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.furnaceBurning.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{Block.cobblestone.blockID},
				{Block.furnaceBurning.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{Block.furnaceBurning.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.signWall.blockID, 4, 0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.doorWood.blockID, 8, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 0, 3},
				{0},
				{Block.torchWood.blockID, 0, 4},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.torchWood.blockID, 0, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 0, 1},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.torchWood.blockID, 0, 2},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 0, 2},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 0, 3},
				{0},
				{Block.torchWood.blockID, 0, 4},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsCobblestone.blockID},
				{0},
			},
			{//x = 4
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsCobblestone.blockID, 3, 0},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 4, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 8
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsCobblestone.blockID, 3, 0},
			},
			{//x = 9
				{0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.bookShelf.blockID},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{Block.signWall.blockID, 5, 0},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 11
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 12
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 13
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.torchWood.blockID, 0, 1},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 0, 3},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 0, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 14
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 15
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 4, 0},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 16
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.bed.blockID, 9, 0},
				{0},
				{Block.bed.blockID, 9, 0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.bed.blockID, 1, 0},
				{0},
				{Block.bed.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 17
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 18
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.torchWood.blockID, 0, 1},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 19
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.ladder.blockID, 4, 0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}																																																																																																																												
			}}};
}