package builder.structures.medieval.twos;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class MillingHouse1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayMillingHouse1 =
	{
		{//y = 0
			{//x = 0
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.doorWood.blockID, 6},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.furnaceIdle.blockID, 3},
				{0},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.furnaceIdle.blockID, 3},
				{SPAWN_VILLAGER, 1, 23},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.furnaceIdle.blockID, 3},
				{Block.ladder.blockID, 4},
				{Block.furnaceIdle.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.doorWood.blockID, 10},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 2
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 4},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.doorWood.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 6
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 7
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 8
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.chest.blockID, 4},
				{Block.chest.blockID, 4},
				{0},
				{Block.chest.blockID, 4},
				{Block.chest.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 10
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 11
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.doorWood.blockID, 10},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.glass.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stainedClay.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 2},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 6},
				{0},
				{Block.trapdoor.blockID, 6},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.thinGlass.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stainedClay.blockID},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.thinGlass.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 7},
				{0},
				{Block.trapdoor.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 6
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 7
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 8
				{Block.wood.blockID, 1},
				{Block.tilledField.blockID},
				{Block.tilledField.blockID},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 9
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			}
		},
		{//y = 11
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.doorWood.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.grass.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 6
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 7
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.wood.blockID, 1},
				{Block.signWall.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.signWall.blockID, 5},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			}
		},
		{//y = 12
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.doorWood.blockID, 10},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			}
		},
		{//y = 13
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.leaves.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.ladder.blockID, 4},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
			}
		},
		{//y = 14
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0}																																																																																																																				
			}}};
}