package builder.structures.modern.houses;

import net.minecraft.block.Block;

public class ModernHouseThree
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayModernHouse3 =
	{
		{//y = 0
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stairsStoneBrick.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stairsStoneBrick.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 7
				{Block.grass.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
			},
			{//x = 9
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
			},
			{//x = 10
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 11
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 12
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 13
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 14
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 15
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 16
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 17
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 18
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.glowStone.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 19
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			}			
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.pressurePlateStone.blockID},
				{0},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.plantYellow.blockID},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 1
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.doorIron.blockID, 2},
				{Block.doorIron.blockID, 2},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 2
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.pressurePlateStone.blockID},
				{Block.pressurePlateStone.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 3
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 16},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 6
				{Block.tallGrass.blockID, 1},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 7
				{Block.plantRed.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 8
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 9
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 10
				{Block.tallGrass.blockID, 1},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 11
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 12
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 13
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 14
				{Block.tallGrass.blockID, 1},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 15
				{Block.tallGrass.blockID, 1},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 16
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 17
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 18
				{Block.tallGrass.blockID, 1},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 19
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.doorIron.blockID, 9},
				{Block.doorIron.blockID, 8},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 14
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 14
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 14
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.blockIron.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.blockIron.blockID},
				{0},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 3
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 4
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 9
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 13
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 14
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 15
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 16
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 17
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 18
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 19
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneSingleSlab.blockID, 8},
			}
		},
		{//y = 6
			{//x = 0
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}