package builder.structures.modern.houses;

import net.minecraft.block.Block;

public class ModernHouseOne
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayModernHouse1 =
	{
		{//y = 0
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
				{Block.grass.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
				{Block.sand.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.dirt.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.sand.blockID},
				{Block.stairsStoneBrick.blockID, 3},
			},
			{//x = 7
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
				{Block.dirt.blockID},
				{Block.stoneSingleSlab.blockID, 8},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 9
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
				{Block.stoneSingleSlab.blockID, 8},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 10
				{Block.grass.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.grass.blockID},
				{Block.stairsStoneBrick.blockID, 3},
				{Block.stairsStoneBrick.blockID},
			},
			{//x = 11
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.dirt.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.grass.blockID},
			},
			{//x = 12
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.sand.blockID},
				{Block.dirt.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.dirt.blockID},
				{Block.sand.blockID},
				{Block.waterStill.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.waterStill.blockID},
				{Block.sand.blockID},
				{Block.grass.blockID},
			},
			{//x = 13
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.sand.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 14
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 1
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantRed.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.plantYellow.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{Block.plantYellow.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{0},
				{Block.reed.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.reed.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
			},
			{//x = 6
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 3},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 16},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.leaves.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.reed.blockID},
				{0},
				{0},
			},
			{//x = 14
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantRed.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{0},
				{Block.reed.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.reed.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
			},
			{//x = 6
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 8},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneButton.blockID, 4},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneButton.blockID, 3},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.leaves.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.reed.blockID},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
			},
			{//x = 6
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{0},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{0},
			},
			{//x = 9
				{0},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{0},
			},
			{//x = 10
				{0},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.leaves.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.reed.blockID},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.reed.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
			},
			{//x = 6
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneDoubleSlab.blockID, 7},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneDoubleSlab.blockID, 7},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneDoubleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.reed.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.reed.blockID},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{Block.reed.blockID},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 9
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
			},
			{//x = 13
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{Block.reed.blockID},
			},
			{//x = 6
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.stoneSingleSlab.blockID, 15},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{Block.ice.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneDoubleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 9
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.stoneSingleSlab.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 13
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.stoneSingleSlab.blockID, 7},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}