package builder.structures.uniquehomes;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class ScaryHouse1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116;

	public static final int[][][][] blockArrayScaryHouse1 =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.leaves.blockID},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.leaves.blockID},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.cloth.blockID},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{Block.leaves.blockID},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.cloth.blockID, 1},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 9
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.cloth.blockID, 1},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.mushroomCapBrown.blockID},
				{Block.cloth.blockID},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stairsStoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 15
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.leaves.blockID},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.pistonBase.blockID, 1},
				{Block.pistonBase.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.leaves.blockID},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.pistonBase.blockID, 1},
				{Block.pistonBase.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.leaves.blockID},
				{Block.leaves.blockID},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.cloth.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.pistonBase.blockID, 1},
				{Block.pistonBase.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID},
				{Block.cloth.blockID, 1},
				{Block.cloth.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.pistonBase.blockID, 1},
				{Block.pistonBase.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.music.blockID},
				{Block.lever.blockID, 9},
				{0},
				{0},
				{0},
				{Block.music.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.jukebox.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.chest.blockID, 5},
				{0},
				{0},
				{Block.signWall.blockID, 4},
				{0},
				{0},
				{Block.signWall.blockID, 4},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.endPortalFrame.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.endPortalFrame.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.furnaceBurning.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.workbench.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.lever.blockID, 2},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.planks.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.dispenser.blockID, 3},
				{Block.bookShelf.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.cake.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
				{0},
				{0},
			},
			{//x = 9
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 15
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 3},
				{Block.trapdoor.blockID, 3},
				{Block.trapdoor.blockID, 3},
				{Block.trapdoor.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.redstoneWire.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.pistonStickyBase.blockID, 9},
				{Block.pistonStickyBase.blockID, 9},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 7
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 8
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 9
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 10
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 11
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 12
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 13
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 14
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 15
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 16
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.endPortalFrame.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.endPortalFrame.blockID, 3},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.bookShelf.blockID},
				{Block.pistonExtension.blockID, 9},
				{Block.pistonExtension.blockID, 9},
				{Block.bookShelf.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.bookShelf.blockID},
				{Block.redstoneWire.blockID, 14},
				{Block.redstoneWire.blockID, 15},
				{Block.bookShelf.blockID},
				{Block.stoneDoubleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 9
				{0},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.jukebox.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.mushroomRed.blockID},
				{Block.bookShelf.blockID},
				{Block.mycelium.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 10
				{0},
				{Block.fenceIron.blockID},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{Block.mycelium.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.fenceGate.blockID, 6},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.pressurePlateStone.blockID},
				{Block.pressurePlateStone.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{0},
				{Block.mushroomBrown.blockID},
				{Block.mycelium.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.fenceGate.blockID, 6},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sand.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 14
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.grass.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 15
				{0},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{0},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.grass.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.brewingStand.blockID},
				{0},
				{0},
				{Block.chest.blockID, 5},
				{Block.chest.blockID, 5},
				{Block.fence.blockID},
				{Block.bookShelf.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
				{Block.grass.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.cauldron.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.grass.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.brewingStand.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.grass.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 7},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{Block.furnaceBurning.blockID, 3},
				{Block.workbench.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.bed.blockID, 9},
				{Block.bed.blockID, 9},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.bed.blockID, 1},
				{Block.bed.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.lever.blockID, 14},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.mushroomRed.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{Block.mushroomBrown.blockID},
				{Block.thinGlass.blockID},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{Block.mushroomBrown.blockID},
				{Block.thinGlass.blockID},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.deadBush.blockID},
				{Block.thinGlass.blockID},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.plantRed.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.fenceIron.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sapling.blockID, 9},
				{Block.wood.blockID},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{Block.signWall.blockID, 5},
				{Block.pressurePlatePlanks.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.sapling.blockID, 8},
				{Block.glass.blockID},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
				{Block.sapling.blockID, 2},
				{Block.glass.blockID},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.plantYellow.blockID},
				{Block.glass.blockID},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 15},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{Block.trapdoor.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.trapdoor.blockID, 2},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sand.blockID},
				{Block.sand.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{Block.dispenser.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.dispenser.blockID, 3},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{Block.dispenser.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.dispenser.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.dispenser.blockID, 3},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{Block.dispenser.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.wood.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 5},
				{Block.chest.blockID, 5},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.bookShelf.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{Block.trapdoor.blockID, 1},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 3},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.trapdoor.blockID, 1},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.bookShelf.blockID},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 3},
				{Block.trapdoor.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}