package builder.structures.nether;

import net.minecraft.block.Block;

public class NetherFarm
{
	public static final int[][][][] blockArrayNetherFarm =
		{
			{// y = 0
				{//x = 0
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 1
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 2
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 3
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 4
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 5
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 6
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 7
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 8
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				}			
			},
			{//y = 1
				{//x = 0
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 1
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 2
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 3
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 4
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 5
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 6
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 7
					{Block.netherrack.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.lavaStill.blockID},
					{Block.slowSand.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 8
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				}			
			},
			{//y = 2
				{//x = 0
					{Block.netherFence.blockID},
					{0},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{0},
					{Block.netherFence.blockID},
				},
				{//x = 1
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 2
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 3
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 4
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 5
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 6
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 7
					{Block.netherFence.blockID},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{0},
					{Block.netherStalk.blockID, 3},
					{Block.netherFence.blockID},
				},
				{//x = 8
					{Block.netherFence.blockID},
					{0},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{0},
					{Block.netherFence.blockID},
				}}};
}