package builder.structures.nether;

import net.minecraft.block.Block;

public class NetherWell 
{
	public static final int[][][][] blockArrayNetherWell =
		{
			{// y = 0
				{//x = 0
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 1
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 2
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 3
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.lavaStill.blockID, 8},
					{Block.lavaStill.blockID, 8},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 4
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.lavaStill.blockID, 8},
					{Block.lavaStill.blockID, 8},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 5
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 6
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 7
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				}			
			},
			{//y = 1
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 2
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 3
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.lavaStill.blockID},
					{Block.lavaStill.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 4
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.lavaStill.blockID},
					{Block.lavaStill.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 5
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 6
					{0},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{0},
				},
				{//x = 7
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}			
			},
			{//y = 2
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.netherBrick.blockID},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.netherBrick.blockID},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 7
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}			
			},
			{//y = 3
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 7
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}			
			},
			{//y = 4
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
					{Block.netherFence.blockID},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 7
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}			
			},
			{//y = 5
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{Block.obsidian.blockID},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 7
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}}};
}
