package builder.structures.nether;

import net.minecraft.block.Block;

public class NetherHouse1 
{
	public static final int SPAWN_VILLAGER = 4100, CUSTOM_SKULL = 4113;
			
	public static final int[][][][] blockArrayNetherHouse1 =
		{
			{// y = 0
				{//x = 0
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 1
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 2
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 3
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 4
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 5
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 6
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				}
			},
			{//y = 1
				{//x = 0
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				},
				{//x = 1
					{Block.netherBrick.blockID},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{Block.lavaStill.blockID},
					{Block.lavaStill.blockID},
					{Block.lavaStill.blockID},
					{Block.lavaStill.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 2
					{Block.netherBrick.blockID},
					{0},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 3
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 4
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 5
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{SPAWN_VILLAGER, 1, 5},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 6
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				}
			},
			{//y = 2
				{//x = 0
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				},
				{//x = 1
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 2
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 3
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 4
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 5
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 6
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				}
			},
			{//y = 3
				{//x = 0
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				},
				{//x = 1
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 2
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 3
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 4
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 5
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 6
					{Block.obsidian.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherFence.blockID},
					{Block.netherFence.blockID},
					{Block.obsidian.blockID},
				}
			},
			{//y = 4
				{//x = 0
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				},
				{//x = 1
					{Block.netherBrick.blockID},
					{Block.glowStone.blockID},
					{0},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{Block.glowStone.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 2
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 3
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 4
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 5
					{Block.netherBrick.blockID},
					{Block.glowStone.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.glowStone.blockID},
					{Block.netherBrick.blockID},
				},
				{//x = 6
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				}
			},
			{//y = 5
				{//x = 0
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				},
				{//x = 1
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 2
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 3
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 4
					{Block.netherBrick.blockID},
					{0},
					{0},
					{Block.slowSand.blockID},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 5
					{Block.netherBrick.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherBrick.blockID},
				},
				{//x = 6
					{Block.obsidian.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.netherBrick.blockID},
					{Block.obsidian.blockID},
				}
			},
			{//y = 6
				{//x = 0
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				},
				{//x = 1
					{Block.netherrack.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherrack.blockID},
				},
				{//x = 2
					{Block.netherrack.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherrack.blockID},
				},
				{//x = 3
					{Block.netherrack.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherrack.blockID},
				},
				{//x = 4
					{Block.netherrack.blockID},
					{0},
					{Block.slowSand.blockID},
					{Block.slowSand.blockID},
					{Block.slowSand.blockID},
					{0},
					{0},
					{Block.netherrack.blockID},
				},
				{//x = 5
					{Block.netherrack.blockID},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{Block.netherrack.blockID},
				},
				{//x = 6
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
					{Block.netherrack.blockID},
				}
			},
			{//y = 7
				{//x = 0
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
				},
				{//x = 1
					{Block.fire.blockID, 15},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID, 3},
					{Block.fire.blockID, 15},
				},
				{//x = 2
					{Block.fire.blockID, 15},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{0},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 3},
					{Block.fire.blockID, 15},
				},
				{//x = 3
					{Block.fire.blockID, 15},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{0},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 3},
					{Block.fire.blockID, 15},
				},
				{//x = 4
					{Block.fire.blockID, 15},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{CUSTOM_SKULL, 1, 1},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 3},
					{Block.fire.blockID, 15},
				},
				{//x = 5
					{Block.fire.blockID, 15},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.fire.blockID, 15},
				},
				{//x = 6
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
					{Block.fire.blockID, 15},
				}
			},
			{//y = 8
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID},
					{Block.stairsNetherBrick.blockID, 3},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 3},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{Block.stairsNetherBrick.blockID, 2},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{Block.stairsNetherBrick.blockID, 1},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}
			},
			{//y = 9
				{//x = 0
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 1
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 2
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 3
					{0},
					{0},
					{0},
					{Block.stoneSingleSlab.blockID, 6},
					{Block.stoneSingleSlab.blockID, 6},
					{0},
					{0},
					{0},
				},
				{//x = 4
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 5
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				},
				{//x = 6
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
					{0},
				}}};
}
