package builder.structures.medieval.inn;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class Inn1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;
	
	public static final int[][][][] blockArrayInn1 =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.lever.blockID, 12, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.lever.blockID, 11, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stone.blockID},
				{0},
				{Block.lever.blockID, 9, 0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.lever.blockID, 9, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.lever.blockID, 12, 0},
				{Block.stoneBrick.blockID, 2, 0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.pistonBase.blockID, 9, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.pistonBase.blockID, 9, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signPost.blockID, 5, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.pistonBase.blockID, 9, 0},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.pistonBase.blockID, 9, 0},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.pistonBase.blockID, 9, 0},
				{Block.stoneBrick.blockID, 1, 0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.doorWood.blockID, 4, 0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.doorWood.blockID, 1, 0},
				{0},
				{0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.signWall.blockID, 3, 0},
				{Block.bookShelf.blockID},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{Block.chest.blockID, 2, 0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stone.blockID},
				{Block.pistonExtension.blockID, 1, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 6, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.furnaceBurning.blockID, 4, 0},
				{Block.furnaceBurning.blockID, 4, 0},
				{Block.cobblestoneMossy.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{Block.signWall.blockID, 5, 0},
				{0},
				{Block.signWall.blockID, 5, 0},
				{Block.doorWood.blockID, 3, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.fence.blockID},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 6, 0},
				{0},
				{Block.signWall.blockID, 5, 0},
				{0},
				{Block.signWall.blockID, 5, 0},
				{Block.fence.blockID},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.fence.blockID},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.pistonExtension.blockID, 1, 1},
				{Block.fence.blockID},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 12, 0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.fence.blockID},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 9, 0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.signWall.blockID, 5, 0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 11, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 14, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 11, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 14, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{Block.stoneBrick.blockID, 2, 0},
				{Block.stoneBrick.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneDoubleSlab.blockID, 2, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.wood.blockID, 2, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.signWall.blockID, 4, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{Block.plantRed.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.signWall.blockID, 4, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.stairsWoodSpruce.blockID, 2, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.signWall.blockID, 5, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.signWall.blockID, 5, 0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.doorWood.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.wood.blockID, 2, 0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{Block.chest.blockID, 2, 0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.bookShelf.blockID},
				{Block.stairsWoodSpruce.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.doorWood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stainedClay.blockID},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 26},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.signWall.blockID, 3, 0},
				{Block.signWall.blockID, 2, 0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.signWall.blockID, 3, 0},
				{Block.fence.blockID},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.furnaceBurning.blockID, 4, 0},
				{Block.furnaceBurning.blockID, 4, 0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};	
}