package builder.structures.npc;

import net.minecraft.block.Block;

public class NPCJail
{
	public static final int[][][][] blockArrayNPCJail =
	{
		{//y = 0
			{//x = 0
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 1},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.bed.blockID},
				{Block.bed.blockID, 8},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.wood.blockID},
				{Block.bed.blockID, 10},
				{Block.bed.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 5
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 3},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.bed.blockID},
				{Block.bed.blockID, 8},
				{Block.wood.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{Block.bed.blockID, 10},
				{Block.bed.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 1},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 3},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.bed.blockID},
				{Block.bed.blockID, 8},
				{Block.planks.blockID},
			},
			{//x = 9
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.thinGlass.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorIron.blockID, 8},	
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.fenceIron.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.cobblestone.blockID},
				{Block.fenceIron.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.lever.blockID, 3},
				{0},
				{Block.doorIron.blockID, 9},
				{0},
				{0},
				{Block.fenceIron.blockID},
			},
			{//x = 5
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 8},
				{0},
				{Block.lever.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.fenceIron.blockID},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{Block.cobblestone.blockID},
				{Block.fenceIron.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.lever.blockID, 3},
				{0},
				{Block.doorIron.blockID, 8},
				{0},
				{0},
				{Block.fenceIron.blockID},
			},
			{//x = 8
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{Block.doorIron.blockID, 8},
				{0},
				{Block.lever.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 9
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 5
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 9
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 3
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}