package builder.structures.medieval.fort;

import net.minecraft.block.Block;

public class Fort3
{
	public static final int[][][][] blockArrayFort3 =
	{
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.furnaceBurning.blockID, 3},
				{Block.furnaceBurning.blockID, 3},
				{Block.furnaceBurning.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneBrick.blockID},
				{Block.workbench.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.stoneBrick.blockID},
				{Block.workbench.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{Block.signWall.blockID, 4},
				{0},
				{Block.signWall.blockID, 4},
				{Block.signWall.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.signWall.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.signWall.blockID, 3},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.workbench.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneDoubleSlab.blockID},
				{Block.glass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 25
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 26
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 28
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.workbench.blockID},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.bookShelf.blockID},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 30
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.ladder.blockID, 3},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.bookShelf.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 25
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{Block.pressurePlatePlanks.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
			},
			{//x = 26
				{0},
				{Block.cobblestone.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 28
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 30
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.cobblestone.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 25
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 26
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.cobblestone.blockID},
				{0},
				{0},
			},
			{//x = 28
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 30
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.stoneBrick.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.fence.blockID},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 25
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 26
				{0},
				{Block.stoneBrick.blockID},
				{Block.ladder.blockID, 3},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 2},
				{Block.stoneBrick.blockID},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{0},
				{0},
			},
			{//x = 28
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.stoneBrick.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stoneBrick.blockID},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 29
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 3},
				{Block.stairsCobblestone.blockID, 1},
				{Block.stairsCobblestone.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 30
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}