package builder.structures.medieval;

import net.minecraft.block.Block;

public class Well
{
	public static final int[][][][] blockArrayWell =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.wood.blockID, 1},
				{0},
			},
			{//x = 2
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
			},
			{//x = 3
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.wood.blockID, 1},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{0},
			},
			{//x = 1
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
			},
			{//x = 2
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
			},
			{//x = 3
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
			},
			{//x = 4
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 2
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{Block.web.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}