package builder.structures.oriental.pagoda;

import net.minecraft.block.Block;

public class JapanPagoda2
{
	public static final int[][][][] blockArrayPagoda2 =
	{
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 6
			{//x = 0
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 9
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 13
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 14
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 15
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 16
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 17
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 18
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 19
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 20
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 21
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 22
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{0},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 23
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 24
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
			},
			{//x = 25
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
			}			
		},
		{//y = 7
			{//x = 0
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
			}			
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.torchWood.blockID, 1},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.torchWood.blockID, 2},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}