package builder.handlers;

import net.minecraft.util.ResourceLocation;

public class Resources 
{
	public static String GuiTexturePrefix = "builder" + ":" + "textures/gui/buildbook/";
	public static String main_GUI = "builder" + ":" + "textures/gui/buildbook/";
	public static String recipe_Images = "builder" + ":" + "textures/gui/buildbook/recipes/";
	public static String activator_Images = "builder" + ":" + "textures/gui/buildbook/activators/";
	public static String info_Images = "builder" + ":" + "textures/gui/buildbook/info/";
	public static String gallery_Images = "builder" + ":" + "textures/gui/buildbook/pics/";
	public static ResourceLocation main_BOOK = new ResourceLocation(main_GUI + "main_buildbook.png");
	public static ResourceLocation main_RECIPE1 = new ResourceLocation(main_GUI + "main_modrecipes1.png");
	public static ResourceLocation main_RECIPE2 = new ResourceLocation(main_GUI + "main_modrecipes2.png");
	public static ResourceLocation main_BLOCKINFO1 = new ResourceLocation(main_GUI + "main_blockinfo1.png");
	public static ResourceLocation main_BLOCKINFO2 = new ResourceLocation(main_GUI + "main_blockinfo2.png");
	public static ResourceLocation main_ACTIVATOR1 = new ResourceLocation(main_GUI + "main_blockinfo1.png");
	public static ResourceLocation main_ACTIVATOR2 = new ResourceLocation(main_GUI + "main_blockinfo2.png");
	public static ResourceLocation main_MODINFO1 = new ResourceLocation(main_GUI + "main_blockinfo2.png");
	public static ResourceLocation main_MODINFO2 = new ResourceLocation(main_GUI + "main_blockinfo2.png");
	public static ResourceLocation rec_BUILDTABLE = new ResourceLocation(recipe_Images + "rec_BUILDTABLE.png");
	public static ResourceLocation rec_HAMMER = new ResourceLocation(recipe_Images + "rec_HAMMER.png");
	public static ResourceLocation rec_SAW = new ResourceLocation(recipe_Images + "rec_SAW.png");
	public static ResourceLocation rec_NAIL = new ResourceLocation(recipe_Images + "rec_NAIL.png");
	public static ResourceLocation rec_NPC = new ResourceLocation(recipe_Images + "rec_NPC.png");
	public static ResourceLocation rec_ORIENTAL = new ResourceLocation(recipe_Images + "rec_ORIENTAL.png");
	public static ResourceLocation rec_MEDIEVAL = new ResourceLocation(recipe_Images + "rec_MEDIEVAL.png");
	public static ResourceLocation rec_VIKING = new ResourceLocation(recipe_Images + "rec_VIKING.png");
	public static ResourceLocation rec_ROMAN = new ResourceLocation(recipe_Images + "rec_ROMAN.png");
	public static ResourceLocation rec_MODERN = new ResourceLocation(recipe_Images + "rec_MODERN.png");
	public static ResourceLocation rec_NETHER = new ResourceLocation(recipe_Images + "rec_NETHER.png");
	public static ResourceLocation rec_RUSSIAN = new ResourceLocation(recipe_Images + "rec_RUSSIAN.png");
	public static ResourceLocation rec_OLDWEST = new ResourceLocation(recipe_Images + "rec_OLDWEST.png");
	public static ResourceLocation rec_UNIQUE = new ResourceLocation(recipe_Images + "rec_UNIQUE.png");
	public static ResourceLocation rec_HALLOW = new ResourceLocation(recipe_Images + "rec_HALLOW.png");
	public static ResourceLocation rec_INDIAN = new ResourceLocation(recipe_Images + "rec_INDIAN.png");
	public static ResourceLocation rec_CHRISTMAS = new ResourceLocation(recipe_Images + "rec_CHRISTMAS.png");
	public static ResourceLocation rec_DESERT = new ResourceLocation(recipe_Images + "rec_DESERT.png");
	public static ResourceLocation rec_JUNGLE = new ResourceLocation(recipe_Images + "rec_JUNGLE.png");
	public static ResourceLocation rec_SWAMP = new ResourceLocation(recipe_Images + "rec_SWAMP.png");
	public static ResourceLocation info_MODINFO = new ResourceLocation(info_Images + "info_MODINFO.png");
	public static ResourceLocation info_NPCINFO = new ResourceLocation(info_Images + "info_NPCINFO.png");
	public static ResourceLocation info_VIKING = new ResourceLocation(info_Images + "info_VIKING.png");
	public static ResourceLocation info_ORIENTAL = new ResourceLocation(info_Images + "orientalinfo.png");
	public static ResourceLocation info_MEDIEVAL = new ResourceLocation(info_Images + "medievalinfo.png");
	public static ResourceLocation info_ROMAN = new ResourceLocation(info_Images + "romaninfo.png");
	public static ResourceLocation info_MODERN = new ResourceLocation(info_Images + "moderninfo.png");
	public static ResourceLocation info_NETHER = new ResourceLocation(info_Images + "netherinfo.png");
	public static ResourceLocation info_RUSSIAN = new ResourceLocation(info_Images + "russianinfo.png");
	public static ResourceLocation info_OLDWEST = new ResourceLocation(info_Images + "oldwestinfo.png");
	public static ResourceLocation info_UNIQUE = new ResourceLocation(info_Images + "uniqueinfo.png");
	public static ResourceLocation info_HALLOW = new ResourceLocation(info_Images + "hallowinfo.png");
	public static ResourceLocation info_INDIAN = new ResourceLocation(info_Images + "indianinfo.png");
	public static ResourceLocation info_CHRISTMAS = new ResourceLocation(info_Images + "oldwestinfo.png");
	public static ResourceLocation info_DESERT = new ResourceLocation(info_Images + "uniqueinfo.png");
	public static ResourceLocation info_JUNGLE = new ResourceLocation(info_Images + "hallowinfo.png");
	public static ResourceLocation info_SWAMP = new ResourceLocation(info_Images + "indianinfo.png");
	public static ResourceLocation activ_NPCACTIV = new ResourceLocation(activator_Images + "npcactivators.png");
	public static ResourceLocation activ_ORIENTAL = new ResourceLocation(activator_Images + "orientalactivators.png");
	public static ResourceLocation activ_MEDIEVAL1 = new ResourceLocation(activator_Images + "medievalactivatorspg1.png");
	public static ResourceLocation activ_MEDIEVAL2 = new ResourceLocation(activator_Images + "medievalactivatorspg2.png");
	public static ResourceLocation activ_VIKING = new ResourceLocation(activator_Images + "vikingactivators.png");
	public static ResourceLocation activ_ROMAN = new ResourceLocation(activator_Images + "romanactivators.png");
	public static ResourceLocation activ_MODERN1 = new ResourceLocation(activator_Images + "modernactivators1.png");
	public static ResourceLocation activ_MODERN2 = new ResourceLocation(activator_Images + "modernactivators2.png");
	public static ResourceLocation activ_NETHER = new ResourceLocation(activator_Images + "netheractivators.png");
	public static ResourceLocation activ_RUSSIAN = new ResourceLocation(activator_Images + "russianactivators.png");
	public static ResourceLocation activ_OLDWEST1 = new ResourceLocation(activator_Images + "oldwestactivatorspg1.png");
	public static ResourceLocation activ_OLDWEST2 = new ResourceLocation(activator_Images + "oldwestactivatorspg2.png");
	public static ResourceLocation activ_UNIQUE = new ResourceLocation(activator_Images + "uniqueactivators.png");
	public static ResourceLocation activ_HALLOW = new ResourceLocation(activator_Images + "hallowactivators.png");
	public static ResourceLocation activ_INDIAN = new ResourceLocation(activator_Images + "indianactivators.png");
	public static ResourceLocation activ_CHRISTMAS = new ResourceLocation(activator_Images + "oldwestactivatorspg2.png");
	public static ResourceLocation activ_DESERT = new ResourceLocation(activator_Images + "uniqueactivators.png");
	public static ResourceLocation activ_JUNGLE = new ResourceLocation(activator_Images + "hallowactivators.png");
	public static ResourceLocation activ_SWAMP = new ResourceLocation(activator_Images + "indianactivators.png");
}
