package builder.structures.oriental.twos;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class JapanDojo1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayDojo1 =
	{
		{//y = 0
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 7
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 9
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 10
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 11
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 12
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 13
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 14
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 15
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 16
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 17
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 18
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 19
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 20
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 21
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 22
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 23
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 24
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 25
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 26
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 27
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 1
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 2
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 3
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 4
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 5
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 6
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{Block.tallGrass.blockID, 1},
				{0},
			},
			{//x = 7
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 10
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 11
				{Block.tallGrass.blockID, 1},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 12
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
			},
			{//x = 13
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.plantYellow.blockID},
			},
			{//x = 14
				{0},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 17
				{Block.tallGrass.blockID, 1},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 18
				{Block.tallGrass.blockID, 1},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 19
				{Block.tallGrass.blockID, 1},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{0},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{0},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.stainedClay.blockID, 8},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.plantYellow.blockID},
			},
			{//x = 25
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
			},
			{//x = 26
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.plantYellow.blockID},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.plantYellow.blockID},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
			},
			{//x = 27
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{Block.tallGrass.blockID, 1},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 2, 0},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.stairsCobblestone.blockID},
				{Block.torchWood.blockID, 2, 0},
				{Block.stairsCobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.torchWood.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.torchWood.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 21},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 21},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 4, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 6, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.stairsCobblestone.blockID, 2, 0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.stairsCobblestone.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{Block.torchWood.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.torchWood.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.stairsCobblestone.blockID, 1, 0},
				{Block.torchWood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 26
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.torchWood.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 12, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 11, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 9, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 14, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.torchWood.blockID, 3, 0},	
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 26
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{Block.woodenButton.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.stoneSingleSlab.blockID, 2, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},	
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{Block.woodenButton.blockID, 4, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.woodenButton.blockID, 3, 0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{Block.woodenButton.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 26
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2, 0},
				{Block.stainedClay.blockID, 1, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1, 12},
				{Block.signWall.blockID, 3, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 23
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 1, 0},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.wood.blockID, 1, 0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 24
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 25
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 26
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 27
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0}
			}}};
}