package builder.structures.oriental.twos;

import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.world.World;

public class JapanGreatHall1
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayGreatHall1 =
	{
		{//y = 0
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 7
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 10
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 11
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 12
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
			},
			{//x = 13
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 14
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 15
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 16
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 17
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 18
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 19
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 20
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 21
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 22
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			}			
		},
		{//y = 1
			{//x = 0
				{0, 15},
				{0, 15},
				{0, 15},
				{0, 15},
				{0},
				{0},
				{0, 15},
				{0},
				{0, 15},
				{0, 15},
				{0, 15},
				{0},
				{0},
			},
			{//x = 1
				{0, 15},
				{0},
				{0, 15},
				{0, 15},
				{0},
				{0, 15},
				{0},
				{0, 15},
				{0, 15},
				{0, 15},
				{0},
				{0, 15},
				{0, 15},
			},
			{//x = 2
				{0, 15},
				{0, 15},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0, 15},
				{0, 15},
			},
			{//x = 3
				{0, 15},
				{0, 15},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0, 15},
				{0, 15},
			},
			{//x = 4
				{0, 15},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0, 15},
			},
			{//x = 5
				{0, 15},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0, 15},
			},
			{//x = 6
				{0, 15},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0, 15},
				{0},
			},
			{//x = 8
				{0},
				{Block.torchWood.blockID, 2},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0, 2},
				{0},
			},
			{//x = 9
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 13
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 14
				{0},
				{Block.torchWood.blockID, 1},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 1},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0, 15},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0, 15},
			},
			{//x = 17
				{0},
				{0},
				{Block.fence.blockID},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{0},
				{Block.wood.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0, 15},
			},
			{//x = 19
				{0, 15},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0, 15},
			},
			{//x = 20
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0, 15},
			},
			{//x = 21
				{0, 15},
				{0},
				{0},
				{0},
				{0, 15},
				{0, 15},
				{0, 15},
				{0},
				{0, 15},
				{0},
				{0},
				{0},
				{0, 15},
			},
			{//x = 22
				{0, 15},
				{0, 15},
				{0, 15},
				{0, 15},
				{0},
				{0, 15},
				{0},
				{0, 15},
				{0},
				{0, 15},
				{0, 15},
				{0, 15},
				{0, 15},
			}			
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 9},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 9},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 9},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 9},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 11},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 11},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 3},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 11},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.bed.blockID, 11},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{Block.stoneSingleSlab.blockID, 2},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{0},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{SPAWN_VILLAGER, 1, 20},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},	
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{SPAWN_VILLAGER, 1, 21},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{0},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{0},
				{Block.trapdoor.blockID, 6},
				{Block.trapdoor.blockID, 6},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.trapdoor.blockID, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.trapdoor.blockID, 5},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{0},
				{Block.trapdoor.blockID, 7},
				{Block.trapdoor.blockID, 7},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 4},
				{Block.signWall.blockID, 4},
				{0},
				{Block.signWall.blockID, 4},
				{Block.signWall.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{Block.signWall.blockID, 5},
				{0},
				{Block.signWall.blockID, 5},
				{Block.signWall.blockID, 5},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{Block.lever.blockID, 2},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.lever.blockID, 3},
				{0},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{0},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{Block.lever.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 2},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 2},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 3
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 9
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 19
				{0},
				{Block.torchWood.blockID, 4},
				{Block.sandStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 3},
				{0},
			},
			{//x = 20
				{0},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{Block.sandStone.blockID},
				{0},
			},
			{//x = 21
				{0},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{0},
				{Block.sandStone.blockID},
				{Block.torchWood.blockID, 1},
				{Block.sandStone.blockID},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}			
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{-113, 2},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 3
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 4
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 5
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 6
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 7
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 8
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 9
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 10
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 11
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 12
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 13
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 14
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 15
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 16
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 17
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 18
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 19
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 20
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{Block.glowStone.blockID},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
			},
			{//x = 21
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
			},
			{//x = 22
				{0},
				{0},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{-113, 1},
				{0},
				{0},
			}			
		},
		{//y = 9
			{//x = 0
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stainedClay.blockID, 1},
				{0},
			},
			{//x = 1
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID, 3},
				{Block.torchWood.blockID, 5},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.torchWood.blockID, 5},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 8
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 9
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 10
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 11
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 12
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 13
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 14
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 15
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 16
				{Block.stoneSingleSlab.blockID, 3},
				{Block.torchWood.blockID, 5},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.torchWood.blockID, 5},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 17
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 18
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 19
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 20
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 21
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
			},
			{//x = 22
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stainedClay.blockID, 1},
				{0},
			}			
		},
		{//y = 10
			{//x = 0
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 2
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{Block.pressurePlateStone.blockID},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.pressurePlateStone.blockID},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stainedClay.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stainedClay.blockID, 1},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
			},
			{//x = 19
				{0},
				{-113, 4},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{Block.stainedClay.blockID, 1},
				{-113, 3},
				{0},
			},
			{//x = 20
				{0},
				{0},
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3},
				{0},
				{0},
			},
			{//x = 21
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
			},
			{//x = 22
				{Block.stoneDoubleSlab.blockID, 3},
				{Block.stoneSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID, 3},
				{Block.stoneDoubleSlab.blockID, 3}
			}}};
}