package builder.structures.swamp;

import net.minecraft.block.Block;

public class SwampFarm
{
	public static final int[][][][] blockArraySwampFarm =
	{
		{//y = 0
			{//x = 0
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 1
			{//x = 0
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 2
			{//x = 0
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 3
			{//x = 0
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
			},
			{//x = 2
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
			},
			{//x = 3
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
			},
			{//x = 4
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
			},
			{//x = 5
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
			},
			{//x = 6
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 4
			{//x = 0
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{Block.wood.blockID, 3},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.wood.blockID, 3},
			},
			{//x = 2
				{Block.wood.blockID, 3},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.wood.blockID, 3},
			},
			{//x = 3
				{Block.wood.blockID, 3},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID, 3},
			},
			{//x = 4
				{Block.wood.blockID, 3},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.wood.blockID, 3},
			},
			{//x = 5
				{Block.wood.blockID, 3},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.wood.blockID, 3},
			},
			{//x = 6
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{0},
			},
			{//x = 2
				{0},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 5
				{0},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}