package builder.structures.swamp;

import net.minecraft.block.Block;

public class SwampHut
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArraySwampHut =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 3
			{//x = 0
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
			},
			{//x = 1
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
			},
			{//x = 2
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
			},
			{//x = 3
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
				{Block.wood.blockID, 7},
			}
		},
		{//y = 4
			{//x = 0
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
			},
			{//x = 2
				{0},
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
			},
			{//x = 3
				{0},
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
			}}};
}