package builder.structures.swamp;

import net.minecraft.block.Block;

public class SwampGardenHouse
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArraySwampGardenHouse =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 1
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 2},
				{Block.planks.blockID, 3},
			},
			{//x = 2
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 2},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{Block.planks.blockID, 3},
			},
			{//x = 4
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 1
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.glowStone.blockID},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 3
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.plantRed.blockID},
				{Block.crops.blockID, 7},
				{Block.crops.blockID, 7},
				{Block.plantRed.blockID},
				{Block.fence.blockID},
			},
			{//x = 5
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 6
				{Block.fenceGate.blockID, 2},
				{0},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 7
				{Block.fence.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.wood.blockID, 11},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{Block.wood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}