package builder.structures.oldwest;

import net.minecraft.block.Block;

public class OldWestSaloon
{
	/** Some predefined values for custom hooks that I use in the demo 
	 * structure 
	 **/
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArraySaloon =
	{
		{//y = 0
			{//x = 0
				{Block.wood.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.woodDoubleSlab.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.wood.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}			
		},
		{//y = 1
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.chest.blockID, 5},//records
				{Block.chest.blockID, 5},//records
				{Block.jukebox.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID, 6},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 36},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 34},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodJungle.blockID, 3},
				{Block.fence.blockID},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{SPAWN_VILLAGER, 1, 32},
				{0},
				{Block.signWall.blockID, 4},
				{Block.signWall.blockID, 4},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 36},
				{0},
				{Block.signWall.blockID, 2},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodJungle.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodJungle.blockID, 2},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 2},
				{Block.woodSingleSlab.blockID, 1},
				{Block.woodSingleSlab.blockID, 1},
				{Block.signWall.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.signWall.blockID, 5},
				{Block.signWall.blockID, 5},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.fenceGate.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 4},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.wood.blockID, 1},
				{Block.workbench.blockID},
				{Block.wood.blockID, 1},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.chest.blockID, 4},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 2
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 6},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.carpet.blockID, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{Block.carpet.blockID, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 3
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 6},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 4},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.chest.blockID, 4},
				{Block.chest.blockID, 4},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.chest.blockID, 4},
				{Block.chest.blockID, 4},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.chest.blockID, 4},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 4
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{Block.stairsWoodSpruce.blockID, 6},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 4},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 5
			{//x = 0
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 6
			{//x = 0
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{Block.fence.blockID},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{Block.fence.blockID},
				{Block.stairsWoodJungle.blockID, 2},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{Block.fence.blockID},
				{Block.stairsWoodJungle.blockID, 2},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 7
			{//x = 0
				{Block.fence.blockID},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{Block.doorWood.blockID, 9},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{Block.carpet.blockID, 12},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.carpet.blockID, 12},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 8
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 5},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 13
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 7},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 4},
				{Block.stairsWoodOak.blockID, 6},
				{Block.planks.blockID, 1},
			},
			{//x = 17
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			}
		},
		{//y = 9
			{//x = 0
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
			},
			{//x = 1
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 2
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 3
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 4
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 5
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 6
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 7
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 8
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 9
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 10
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 11
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 12
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 13
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 14
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 15
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 16
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 17
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 3
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 4
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 5
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 6
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 7
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 8
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 9
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 10
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 11
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 12
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 13
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 14
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 15
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 16
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}