package builder.structures.oldwest;

import net.minecraft.block.Block;

public class OldWestWaterTower
{
	public static final int[][][][] blockArrayWaterTower =
	{
		{//y = 0
			{//x = 0
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 1
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 2
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 3
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 4
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 5
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 6
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 7
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 8
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			},
			{//x = 9
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 7
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			},
			{//x = 9
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 3
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 4
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 5
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 7
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 8
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 9
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 3
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{Block.fence.blockID},
				{Block.lever.blockID, 12},
				{Block.wood.blockID},
				{Block.pistonBase.blockID, 11},
				{Block.pistonExtension.blockID, 3},
				{Block.wood.blockID},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{Block.fence.blockID},
				{Block.lever.blockID, 12},
				{Block.wood.blockID},
				{Block.pistonBase.blockID, 11},
				{Block.pistonExtension.blockID, 3},
				{Block.wood.blockID},
				{0},
				{Block.fence.blockID},
			},
			{//x = 6
				{Block.fence.blockID},
				{Block.lever.blockID, 12},
				{Block.wood.blockID},
				{Block.pistonBase.blockID, 11},
				{Block.pistonExtension.blockID, 3},
				{Block.wood.blockID},
				{0},
				{Block.fence.blockID},
			},
			{//x = 7
				{Block.fence.blockID},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 11
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 5
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 6
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.wood.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.woodSingleSlab.blockID},
				{Block.wood.blockID},
				{Block.wood.blockID},
				{Block.woodSingleSlab.blockID},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 12
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 13
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}