package builder.structures.oldwest;

import net.minecraft.block.Block;

public class OldWestBlackSmith
{
	/** Some predefined values for custom hooks that I use in the demo 
	 * structure 
	 **/
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayBlackSmith =
	{
		{//y = 0
			{//x = 0
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 1
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 3
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 4
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 5
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 7
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 8
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 9
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 10
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 11
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			},
			{//x = 12
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 1
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.chest.blockID, 5},
				{Block.chest.blockID, 5},
				{0},
				{Block.ladder.blockID, 5},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 3
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 4},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 10
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 11
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.ladder.blockID, 4},
				{0},
				{Block.furnaceIdle.blockID, 4},
				{Block.furnaceIdle.blockID, 4},
				{Block.workbench.blockID},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 12
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 5},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{Block.ladder.blockID, 4},
				{0},
				{Block.furnaceIdle.blockID, 4},
				{Block.furnaceIdle.blockID, 4},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 12
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.ladder.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 12
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 1
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.ladder.blockID, 5},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			},
			{//x = 9
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.ladder.blockID, 4},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 12
				{Block.fence.blockID},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{Block.fence.blockID},
			}
		},
		{//y = 5
			{//x = 0
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 1
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.bed.blockID, 10},
				{Block.bed.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 2
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.chest.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 3
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 4
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 5
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 6
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 7
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 8
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 9
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 10
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 11
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{Block.bed.blockID},
				{Block.bed.blockID, 8},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 12
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 1
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 2
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 4
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 5
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 6
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 8
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 9
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 10
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 11
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 12
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{Block.wood.blockID, 4},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}				