package builder.structures.oldwest;

import net.minecraft.block.Block;

public class OldWestJail
{
	/** Some predefined values for custom hooks that I use in the demo 
	 * structure 
	 **/
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayOldWestJail =
	{
		{//y = 0
			{//x = 0
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.gravel.blockID},
			},
			{//x = 1
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 2
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 3
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 4
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 5
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 6
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.grass.blockID},
			},
			{//x = 7
				{Block.grass.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.gravel.blockID},
				{Block.gravel.blockID},
			},
			{//x = 8
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.grass.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.gravel.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 1
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 35},
				{0},
				{Block.chest.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.planks.blockID, 1},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.stoneSingleSlab.blockID, 5},
				{Block.fenceIron.blockID},
				{0},
				{Block.stairsWoodSpruce.blockID, 7},
				{Block.stairsWoodSpruce.blockID, 6},
				{0},
				{Block.chest.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 1
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 2
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fenceIron.blockID},
				{Block.fenceIron.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID},
				{Block.fence.blockID},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
			},
			{//x = 1
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 2
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 3
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 4
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 6},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 5
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 6
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{Block.fenceIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 7
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 3},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
			},
			{//x = 1
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.torchWood.blockID, 5},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodSpruce.blockID, 2},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
			}}};
}				