package builder.structures.oldwest;

import net.minecraft.block.Block;

public class OldWestStable
{
	/** Some predefined values for custom hooks that I use in the demo 
	 * structure 
	 **/
	public static final int SPAWN_HORSE1 = 4102, SPAWN_HORSE2 = 4103;

	public static final int[][][][] blockArrayOldWestStable =
	{
		{//y = 0
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{Block.hay.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.hay.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_HORSE1},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{Block.chest.blockID, 4},
				{Block.chest.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.fenceGate.blockID, 1},
				{Block.fenceGate.blockID, 1},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 10
				{0},
				{Block.fenceGate.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fenceGate.blockID, 2},
			},
			{//x = 11
				{0},
				{Block.fenceGate.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fenceGate.blockID},
			},
			{//x = 12
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 13
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 13
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.fence.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 10
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 11
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 12
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 13
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.stairsWoodSpruce.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{Block.stairsWoodSpruce.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 10
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 11
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 12
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.wood.blockID, 4},
				{0},
				{Block.ladder.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 2
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 3
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 4
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 5
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 6
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 7
				{0},
				{Block.wood.blockID, 4},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID, 4},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID, 8},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 10
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 11
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.ladder.blockID, 5},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 10
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{Block.hay.blockID, 4},
				{0},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{0},
				{Block.fenceGate.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{Block.fence.blockID},
				{0},
				{Block.hay.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.hay.blockID},
				{Block.hay.blockID, 4},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{Block.hay.blockID, 8},
				{Block.hay.blockID},
				{Block.fence.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 9
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.wood.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.planks.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.woodSingleSlab.blockID, 9},
				{Block.planks.blockID},
			},
			{//x = 8
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
			},
			{//x = 1
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.planks.blockID},
			},
			{//x = 7
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
			},
			{//x = 2
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.planks.blockID},
			},
			{//x = 6
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
			},
			{//x = 3
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.stairsWoodSpruce.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 4
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.stairsWoodSpruce.blockID, 4},
				{Block.planks.blockID},
			},
			{//x = 5
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
				{Block.stairsWoodSpruce.blockID},
			},
			{//x = 4
				{0},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
				{Block.stairsWoodSpruce.blockID, 1},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}				