package builder.structures.modern;

import net.minecraft.block.Block;

public class ModernBigHouse
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayModernBigHouse =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.wood.blockID, 3},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 8
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 9
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 10
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 13
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 14
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 15
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 16
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.stainedClay.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.oreNetherQuartz.blockID},
				{Block.blockIron.blockID},
				{Block.doorWood.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.leaves.blockID, 7},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 16},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 10
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 13
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.doorWood.blockID, 8},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.leaves.blockID, 7},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 10
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 13
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.leaves.blockID, 7},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 3
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID},
				{Block.stairsWoodJungle.blockID},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 10
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 13
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.wood.blockID, 3},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.blockIron.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 8
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 9
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 10
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 13
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
			},
			{//x = 2
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 10
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 12
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 13
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 14
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 15
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.blockIron.blockID},
			},
			{//x = 16
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.blockIron.blockID},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.stairsWoodJungle.blockID, 1},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 10
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 14
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 9
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 15
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 8
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.stairsNetherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 16
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			}
		},
		{//y = 9
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 5
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 6
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 3},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.stairsNetherBrick.blockID, 1},
				{Block.blockIron.blockID},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 17
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 18
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			}
		},
		{//y = 10
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}