package builder.structures.modern;

import net.minecraft.block.Block;

public class ModernBlackSmith
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayModernBlackSmith =
	{
		{//y = 0
			{//x = 0
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.oreCoal.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsStoneBrick.blockID, 1},
				{Block.stairsStoneBrick.blockID, 1},
				{Block.stairsStoneBrick.blockID, 1},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 1
				{Block.blockNetherQuartz.blockID},
				{Block.stairsWoodSpruce.blockID, 3},
				{Block.stairsNetherQuartz.blockID, 1},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.lavaStill.blockID},
				{Block.lavaStill.blockID},
				{Block.stoneBrick.blockID, 3},
			},
			{//x = 2
				{Block.blockNetherQuartz.blockID},
				{Block.stairsNetherQuartz.blockID, 3},
				{Block.fence.blockID},
				{0},
				{SPAWN_VILLAGER, 1, 14},
				{0},
				{Block.chest.blockID, 2},
				{Block.stoneBrick.blockID, 2},
				{Block.stoneBrick.blockID, 3},
				{Block.stoneBrick.blockID, 3},
				{Block.stoneBrick.blockID, 2},
			},
			{//x = 3
				{Block.blockNetherQuartz.blockID},
				{Block.stairsNetherQuartz.blockID, 3},
				{0},
				{0},
				{0},
				{Block.oreNetherQuartz.blockID},
				{Block.oreNetherQuartz.blockID},
				{Block.stoneBrick.blockID, 3},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 4
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 5
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.anvil.blockID},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 1
				{Block.blockNetherQuartz.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.stoneBrick.blockID, 3},
				{0},
				{0},
				{Block.fenceIron.blockID},
			},
			{//x = 2
				{Block.thinGlass.blockID},
				{0},
				{Block.carpet.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 3},
				{0},
				{0},
				{Block.fenceIron.blockID},
			},
			{//x = 3
				{Block.oreNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{Block.oreNetherQuartz.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{Block.oreNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 1
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 3},
			},
			{//x = 2
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneBrick.blockID, 3},
				{0},
				{0},
				{Block.stoneBrick.blockID, 3},
			},
			{//x = 3
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.oreNetherQuartz.blockID},
				{Block.oreNetherQuartz.blockID},
				{Block.furnaceIdle.blockID, 5},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{Block.blockNetherQuartz.blockID},
				{0},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{Block.fence.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockNetherQuartz.blockID},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockNetherQuartz.blockID},
				{Block.blockIron.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 6
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 7
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}