package builder.structures.modern;

import net.minecraft.block.Block;

public class ModernFarm
{
	public static final int[][][][] blockArrayModernFarm =
	{
		{//y = 0
			{//x = 0
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 1
				{Block.stoneDoubleSlab.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.dirt.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 2
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 3
				{Block.stoneDoubleSlab.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 4
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 5
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 6
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 7
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 8
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 9
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 10
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.dirt.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 11
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 12
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 13
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 14
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 15
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.waterStill.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 16
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 17
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.tilledField.blockID, 7},
				{Block.waterStill.blockID},
				{Block.tilledField.blockID, 7},
				{Block.stoneDoubleSlab.blockID},
			},
			{//x = 18
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
				{Block.stoneDoubleSlab.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{Block.melon.blockID},
				{0},
				{0},
				{0},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{Block.pumpkin.blockID, 1},
				{0},
			},
			{//x = 2
				{0},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{Block.melonStem.blockID, 7},
				{0},
				{0},
				{0},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{Block.pumpkinStem.blockID, 7},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 8
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 9
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 10
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 11
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 12
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 13
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 14
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{Block.carrot.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 15
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 16
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 17
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{0},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{Block.potato.blockID, 7},
				{0},
				{0},
				{Block.crops.blockID, 7},
				{0},
				{Block.crops.blockID, 7},
				{0},
			},
			{//x = 18
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}