package builder.structures.modern;

import net.minecraft.block.Block;

public class ModernHut
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayModernHut =
	{
		{//y = 0
			{//x = 0
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 1
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 2
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{Block.stairsStoneBrick.blockID, 3},
			},
			{//x = 3
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 4
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 5
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{Block.stone.blockID},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{Block.stone.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 1
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 2
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
			},
			{//x = 3
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 4
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 15},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 5
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{Block.stone.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 1
				{Block.netherBrick.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 1},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 2
				{Block.netherBrick.blockID},
				{Block.torchWood.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
			},
			{//x = 3
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 4
				{Block.netherBrick.blockID},
				{0},
				{0},
				{Block.torchWood.blockID, 2},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 5
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.glass.blockID},
				{Block.stone.blockID},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{Block.stone.blockID},
				{Block.glass.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 1
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 2
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
			},
			{//x = 3
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stone.blockID},
				{0},
			},
			{//x = 4
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 5
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.glass.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			},
			{//x = 1
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 2
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 3
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 4
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{0},
			},
			{//x = 5
				{Block.stone.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.stone.blockID},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 1
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 2
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 3
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 4
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
			},
			{//x = 5
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{Block.stoneSingleSlab.blockID},
				{0},
			}}};
}