package builder.structures.modern;

import net.minecraft.block.Block;

public class ModernBigHouseGarden
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int CUSTOM_CHEST1 = 4116, SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayBigHouseGarden =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{Block.stoneSingleSlab.blockID},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 8
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 9
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 10
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 12
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 13
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 14
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{Block.stoneSingleSlab.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.doorWood.blockID},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.flowerPot.blockID, 9},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 3
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
				{0},
			},
			{//x = 4
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 5
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 6
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 7
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 8
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 9
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 13},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 10
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 11
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 12
				{Block.glass.blockID},
				{0},
				{Block.fence.blockID},
				{Block.woodSingleSlab.blockID, 9},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 9},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{Block.lever.blockID, 4},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 13
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.flowerPot.blockID, 9},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{Block.redstoneLampIdle.blockID},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 14
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.doorWood.blockID, 2},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.doorWood.blockID, 8},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 3
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.flowerPot.blockID, 6},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 6},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
				{0},
			},
			{//x = 4
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 11},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 5
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 1},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 6
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 7},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 7
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 8
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 9
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 7},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 7},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 10
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 2},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 2},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 11
				{Block.glass.blockID},
				{0},
				{0},
				{Block.flowerPot.blockID, 11},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 11},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{0},
				{0},
				{Block.flowerPot.blockID, 6},
				{0},
				{0},
				{0},
				{Block.flowerPot.blockID, 6},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 13
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 14
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.doorWood.blockID, 8},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 3
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 4
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 5
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 6
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
			},
			{//x = 7
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
			},
			{//x = 8
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 9
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 10
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
			},
			{//x = 11
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
			},
			{//x = 12
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 13
				{Block.planks.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 2},
				{0},
			},
			{//x = 14
				{Block.blockIron.blockID},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.planks.blockID, 3},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 2},
				{Block.woodSingleSlab.blockID, 2},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 2
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 3
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 4
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 5
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 6
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 7
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 8
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 9
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 10
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 11
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 12
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 13
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.stairsWoodJungle.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 14
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.redstoneLampIdle.blockID},
				{Block.lever.blockID, 3},
				{Block.bed.blockID, 9},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.bed.blockID, 1},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.chest.blockID, 2},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.glass.blockID},
				{0},
				{Block.glass.blockID},
				{Block.glowStone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.glass.blockID},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 7
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.planks.blockID, 2},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}
		},
		{//y = 8
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 4
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 5
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 6
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 11
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 12
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 13
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.netherBrick.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{Block.blockIron.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
			}}};
}