package builder.structures.halloweentown;

import net.minecraft.block.Block;

public class HallowCube
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayCube =
	{
		{//y = 0
			{//x = 0
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 1
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 2
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 3
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 4
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 5
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 6
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.lever.blockID, 13},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 7
				{Block.obsidian.blockID},
				{Block.obsidian.blockID},
				{Block.obsidian.blockID},
				{Block.obsidian.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestoneMossy.blockID},
				{Block.obsidian.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.obsidian.blockID},
			},
			{//x = 1
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID, 1},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 9},//Farmer
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.doorWood.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.redstoneLampActive.blockID},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.web.blockID},
				{Block.planks.blockID, 1},
				{Block.obsidian.blockID},
			},
			{//x = 1
				{Block.planks.blockID, 1},
				{Block.fence.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.doorWood.blockID, 8},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 6
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.thinGlass.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.obsidian.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 1
				{Block.planks.blockID, 1},
				{Block.pumpkinLantern.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.planks.blockID, 1},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			},
			{//x = 1
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 2
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 3
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 4
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 5
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 6
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
			},
			{//x = 7
				{Block.cobblestoneMossy.blockID},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.planks.blockID, 1},
				{Block.cobblestoneMossy.blockID},
			}
		},
		{//y = 5
			{//x = 0
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 1
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 2
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 3
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 4
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 5
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 6
				{Block.woodSingleSlab.blockID, 3},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.woodSingleSlab.blockID, 3},
			},
			{//x = 7
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
				{Block.woodSingleSlab.blockID, 3},
			}}};
}