package builder.structures.halloweentown;

import net.minecraft.block.Block;

public class HallowBigHouse
{
	/** Some predefined values for custom hooks that I use in the demo structure */
	public static final int SPAWN_VILLAGER = 4100;

	public static final int[][][][] blockArrayBigHouse =
	{
		{//y = 0
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 1
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 1},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{SPAWN_VILLAGER, 1, 11},//villager
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestoneMossy.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.cobblestoneMossy.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 2
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 5},
				{Block.planks.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{Block.torchWood.blockID, 5},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.thinGlass.blockID},
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.wood.blockID},
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.doorWood.blockID, 8},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
				{Block.wood.blockID},
				{Block.thinGlass.blockID},
				{Block.thinGlass.blockID},
				{Block.wood.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 3
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			},
			{//x = 1
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 2
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
			},
			{//x = 3
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 4
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 5
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 6
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 7
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 8
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 9
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.cobblestone.blockID},
			},
			{//x = 10
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 11
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 12
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 13
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 14
				{Block.cobblestone.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 15
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{Block.torchWood.blockID, 4},
				{Block.planks.blockID},
			},
			{//x = 16
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
				{Block.cobblestone.blockID},
			}
		},
		{//y = 4
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 2
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 3
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 4
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 5
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 6
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 7
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 8
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 9
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 10
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 11
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 12
				{Block.thinGlass.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 13
				{Block.wood.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 14
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 15
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
			}
		},
		{//y = 5
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 3
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 4
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 5
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 6
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 7
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 10
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 11
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 12
				{Block.planks.blockID},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 13
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 14
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
			}
		},
		{//y = 6
			{//x = 0
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 1
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 2
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 3
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 4
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 5
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 6
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 7
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 8
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 9
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 10
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 11
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.stairsWoodOak.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 12
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 13
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.stairsWoodOak.blockID, 1},
				{Block.planks.blockID},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 14
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 15
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 16
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			},
			{//x = 17
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{0},
				{Block.stairsWoodOak.blockID, 2},
				{Block.stairsWoodOak.blockID, 3},
				{0},
				{0},
			}}};
}